user_pref("accessibility.force_disabled", 1);  
user_pref("accessibility.typeaheadfind.flashBar", 0);  
user_pref("app.normandy.first_run", false);  
user_pref("app.shield.optoutstudies.enabled", false);  
user_pref("app.update.auto", false);  
user_pref("app.update.checkInstallTime", false);  
user_pref("app.update.doorhanger", false);  
user_pref("browser.feeds.showFirstRunUI", false);  
user_pref("browser.newtabpage.activity-stream.feeds.section.highlights", false);  
user_pref("browser.newtabpage.activity-stream.feeds.snippets", false);  
user_pref("browser.newtabpage.activity-stream.feeds.telemetry", false);  
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);  
user_pref("browser.newtabpage.activity-stream.prerender", false);  
user_pref("browser.newtabpage.activity-stream.telemetry", false);  
user_pref("browser.newtabpage.activity-stream.telemetry.ping.endpoint", "[https://localhost](https://localhost "https://localhost")");  
user_pref("browser.ping-centre.telemetry", false);  
user_pref("browser.safebrowsing.blockedURIs.enabled", false);  
user_pref("browser.safebrowsing.downloads.enabled", false);  
user_pref("browser.safebrowsing.downloads.remote.block_dangerous", false);  
user_pref("browser.safebrowsing.downloads.remote.block_dangerous_host", false);  
user_pref("browser.safebrowsing.downloads.remote.block_potentially_unwanted", false);  
user_pref("browser.safebrowsing.downloads.remote.block_uncommon", false);  
user_pref("browser.safebrowsing.downloads.remote.enabled", false);  
user_pref("browser.safebrowsing.downloads.remote.url", "[https://localhost](https://localhost "https://localhost")");  
user_pref("browser.safebrowsing.malware.enabled", false);  
user_pref("browser.safebrowsing.phishing.enabled", false); user_pref("browser.safebrowsing.provider.google.advisoryURL", "[https://localhost](https://localhost "https://localhost")'");  
user_pref("browser.safebrowsing.provider.google.gethashURL", "[https://localhost](https://localhost "https://localhost")");  
user_pref("browser.safebrowsing.provider.google.lists", "[https://localhost](https://localhost "https://localhost")");  
user_pref("browser.safebrowsing.provider.google.reportMalwareMistakeURL", "[https://localhost](https://localhost "https://localhost")");  
user_pref("browser.safebrowsing.provider.google.reportPhishMistakeURL", "[https://localhost](https://localhost "https://localhost")");  
user_pref("browser.safebrowsing.provider.google.reportURL", "[https://localhost](https://localhost "https://localhost")");  
user_pref("browser.safebrowsing.provider.google.updateURL", "[https://localhost](https://localhost "https://localhost")");  
user_pref("browser.safebrowsing.provider.google4.advisoryURL", "[https://localhost](https://localhost "https://localhost")");  
user_pref("browser.safebrowsing.provider.google4.dataSharingURL", "[https://localhost](https://localhost "https://localhost")");  
user_pref("browser.safebrowsing.provider.google4.gethashURL", "[https://localhost](https://localhost "https://localhost")");  
user_pref("browser.safebrowsing.provider.google4.reportMalwareMistakeURL", "[https://localhost](https://localhost "https://localhost")");  
user_pref("browser.safebrowsing.provider.google4.reportPhishMistakeURL", "[https://localhost](https://localhost "https://localhost")");  
user_pref("browser.safebrowsing.provider.google4.reportURL", "[https://localhost](https://localhost "https://localhost")");  
user_pref("browser.safebrowsing.provider.google4.updateURL", "[https://localhost](https://localhost "https://localhost")");  
user_pref("browser.safebrowsing.provider.mozilla.gethashURL", "[https://localhost](https://localhost "https://localhost")");  
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "995795774646");  
user_pref("browser.safebrowsing.provider.mozilla.updateURL", "[https://localhost](https://localhost "https://localhost")");  
user_pref("browser.safebrowsing.reportPhishURL", "[https://localhost](https://localhost "https://localhost")");  
user_pref("browser.search.geoSpecificDefaults.url", "[https://localhost](https://localhost "https://localhost")");  
user_pref("browser.search.searchEnginesURL", "[https://localhost](https://localhost "https://localhost")");  
user_pref("browser.search.suggest.enabled", false);  
user_pref("browser.search.update", false);  
user_pref("browser.search.update.interval", 995795774646);  
user_pref("browser.startup.page", 0);  
user_pref("browser.urlbar.suggest.bookmark", false);  
user_pref("browser.urlbar.suggest.history", false);  
user_pref("captivedetect.maxRetryCount", 0);  
user_pref("experiments.activeExperiment", false);  
user_pref("experiments.manifest.uri", "[https://localhost](https://localhost "https://localhost")");  
user_pref("extensions.update.enabled", false);  
user_pref("general.warnOnAboutConfig", false);  
user_pref("network.captive-portal-service.enabled", false);  
user_pref("security.ssl.errorReporting.url", "[https://localhost](https://localhost "https://localhost")");  
user_pref("services.settings.server", "[https://localhost](https://localhost "https://localhost")");  
user_pref("services.sync.nextSync", 0);  
user_pref("services.sync.prefs.sync.browser.safebrowsing.downloads.enabled", false);  
user_pref("services.sync.prefs.sync.browser.safebrowsing.malware.enabled", false);  
user_pref("services.sync.prefs.sync.browser.safebrowsing.passwords.enabled", false);  
user_pref("services.sync.prefs.sync.browser.safebrowsing.phishing.enabled", false);  
user_pref("toolkit.telemetry.archive.enabled", false);  
user_pref("toolkit.telemetry.bhrPing.enabled", false);  
user_pref("toolkit.telemetry.firstShutdownPing.enabled", false);  
user_pref("toolkit.telemetry.hybridContent.enabled", false);  
user_pref("toolkit.telemetry.newProfilePing.enabled", false);  
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);  
user_pref("toolkit.telemetry.shutdownPingSender.enabled", false);  
user_pref("toolkit.telemetry.unified", false);  
user_pref("toolkit.telemetry.updatePing.enabled", false);  
user_pref("browser.newtabpage.activity-stream.section.highlights.includePocket", false);  
user_pref("extensions.pocket.enabled", false);  
user_pref("services.sync.prefs.sync.browser.newtabpage.activity-stream.section.highlights.includePocket", false);